services:
  - type: web
    plan: free
    region: frankfurt
    name: json_viewer
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --bind=localhost:8000"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.9.17